### ISSUE TITLE
cuDNN error

### ISSUE THREAD

**Issue by GsyHugh** [962086838/Battery_fault_detection_NC_github#2]
I'm running Ubuntu 20.04, cuda 10.2, cuDNN 7.6.5. Conda environment is set up as readme instructed. However I'm running into cuDNN error, full error is shown below.
```
Loaded configs at model_params_battery_brand1.json
args Namespace(anneal0=0.01, anneal_function='linear', batch_size=128, bidirectional=True, config_path='model_params_battery_brand1.json', cosine_factor=0.1, dim_feedforward=2048, epochs=3, evaluation_path='../data/battery_brand1/label', fold_num=0, granularity_all=1000, granularity_car=1000, hidden_size=128, jobs=32, k=0.0025, kernel_size=3, latent_label_weight=0.001, latent_size=8, learning_rate=0.005, min_length=30, model_type='rnn', nhead=2, nll_weight=10, noise_scale=1, num_granularity_all=100, num_granularity_car=200, num_layers=2, project='project', rnn_type='gru', save_model_path='./dyad_vae_save', smoothing=False, task='batterybranda', test_path='../data/battery_brand1/test', train_path='../data/battery_brand1/train', use_flag='rec_error', variable_length=False, x0=500)
train start............................
Loading data to memory. This may take a few minutes...
car_number is  [10, 7, 146, 166, 48, 75, 86, 15, 175, 64, 2, 110, 13, 23, 93, 116, 62, 8, 41, 22, 6, 24, 101, 46, 187, 198, 142, 131, 18, 160, 56, 29, 141, 148, 168, 71, 53, 104, 120, 154, 20, 17, 111, 133, 63, 35, 83, 5, 88, 159, 145, 176, 127, 77, 118, 52, 81, 121, 59, 38, 80, 109, 179, 28, 123, 44, 180, 149, 135, 164, 74, 40, 14, 65, 69, 42, 193, 12, 60, 73, 126, 161, 188, 32, 30, 170, 128, 167, 9, 155, 156, 43, 100, 33, 90, 139, 1, 112, 25, 4, 16, 189, 147, 124, 178, 55, 85, 122, 96, 162, 132, 89, 19, 27, 84, 39, 151, 67, 26, 172, 76, 37, 143, 58, 165, 97, 134, 82, 113, 137, 144, 70, 11, 117, 106]
Data loaded successfully.
model DynamicVAE(
  (encoder_rnn): GRU(7, 128, num_layers=2, batch_first=True, bidirectional=True)
  (decoder_rnn): GRU(2, 128, num_layers=2, batch_first=True, bidirectional=True)
  (hidden2mean): Linear(in_features=512, out_features=8, bias=True)
  (hidden2log_v): Linear(in_features=512, out_features=8, bias=True)
  (latent2hidden): Linear(in_features=8, out_features=512, bias=True)
  (outputs2embedding): Linear(in_features=256, out_features=5, bias=True)
  (mean2latent): Sequential(
    (0): Linear(in_features=8, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
)
training:   0%|                                                                                                                        | 0/8265 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main_five_fold.py", line 28, in <module>
    tr.main()
  File "/GSY_FD/Battery_Fault_Detection/DyAD/train.py", line 133, in main
    seq_lengths=seq_lengths, noise_scale=self.args.noise_scale)
  File "/home/user/anaconda3/envs/GSY_BFD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/GSY_FD/Battery_Fault_Detection/DyAD/model/dynamic_vae.py", line 40, in forward
    output, hidden = self.encoder_rnn(en_input_embedding)
  File "/home/user/anaconda3/envs/GSY_BFD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/GSY_BFD/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 727, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
training:   0%|                                                                                                                        | 0/8265 [00:01<?, ?it/s]
```
Could you please provide detailed experiment platform: ubuntu, cuda, cudnn. Much appreciated.

**Comment by tpnam0901** [comment]
Hi @GsyHugh, I have successfully run it with Pytorch 2.1.0 and CUDA 11.8. You can follow my installation or use this [docker image](https://hub.docker.com/r/namphuongtran9196/battery-dyad).

Install torch2.1.0+cu118
Install requirements.txt with the below lib.
```
pyod==0.9.7
easydict
matplotlib
pandas
requests
scikit-learn
seaborn
tqdm
zipfile36
scipy
tensorflow
```

 run after installing correct Pytorch package
```
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-2.1.0+cu118.html
pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-2.1.0+cu118.html
pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-2.1.0+cu118.html
pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-2.1.0+cu118.html
pip install torch-geometric==2.1.0
```
